---
title: "Graph Testing"
author: "Me" 
abstract: this is the abstact/description for the document.
execute:   
  echo: false  # this will turn it off
---


## Basic Plot Types


We also looked at both width and length, as seen in @fig-scatterplot. blah blah blah.

```{r}
#| label: fig-scatterplot
#| fig-cap: "Scatter plot of sepal length and width values for three iris species."
plot( Sepal.Length ~ Sepal.Width, 
      data = iris, 
      xlab = "Sepal Width (cm)",
      ylab = "Sepal Length (cm) ",
      col = as.numeric( iris$Species ),
      pch = 16) 
legend( 3.75, 7.5, 
        legend = levels( iris$Species ),
        col = 1:3, 
        pch = 16,
        bty = "n")
```


```{r}
x <- c(23, 32,44, 12, 2, 19)
colors <- c("#7fc97f", "#beaed4", "#fdc086", "#ffff99", "#386cb0", "#f0027f")
pie( x, 
     labels = c("Rodney","Heather", "Sid", "Heidi", "Mark", "Marie"), 
     col = colors )
```


```{r}
barplot( x,
         names.arg = c("Rodney","Heather", "Sid", "Heidi", "Mark", "Marie"),
         xlab = "People",
         ylab = "Some value associated (units)",
         col = "yellow",
         border = "orange")
```




*Error Bars*


```{r}
library( tidyverse )
iris %>%
  group_by( Species ) %>%
  summarize( Mean = mean( Sepal.Length ), 
             SD = sd( Sepal.Length) )  %>%
  mutate( Label = paste( "I.", Species ) ) %>%
    mutate( EB = Mean + 2*SD) -> iris.summary
barplot( iris.summary$Mean, 
         names.arg = iris.summary$Label,
         ylab = "Sepal Length (cm)",
         ylim = c(0,10) )
arrows( 1:3, iris.summary$Mean,
        1:3, iris.summary$EB,
        angle = 90, 
        lwd = 2)

```


```{r}
boxplot( Sepal.Length ~ Species , 
         data = iris, 
         horizontal = FALSE, 
         notch = TRUE)
```






*histogram*

We measured the sepal lengths of three iris species (@fig-sepallength)

```{r}
#| echo: true
#| fig-cap: "My cool distriubtion of sepal lengths (cm)."
#| label: fig-sepallength
hist( iris$Sepal.Length, 
      xlab="Sepal Lenght (cm)",
      main = "",
      col = "cadetblue4"
      )
```

